name: Tests
on:
  workflow_run:
    workflow:
      - Run Tests
    types:
      - completed 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
permissions:
  contents: read
  pull-requests: read 
jobs:
  test:
    name: Check tests 
    run-on: ubuntu-20.04
steps:
- uses: actions/checkout@v3
- name: Set up Python
  uses: actions/setup-python@v4
  with:
    python-version: '3.11'
    cache: 'pip'
- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
- name: Lint with Ruff
  run: |
    pip install ruff
    ruff --format=github --target-version=py37 .
  continue-on-error: true
